apiVersion: apps/v1
kind: Deployment
metadata:
  name: did-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: did
  template:
    metadata:
      labels:
        app: did
    spec:
      containers:
        - name: did
          image: fibrinlab/did
          env:
            - name: OPERATOR_ID
              value: '0.0.4560302'
            - name: OPERATOR_KEY
              value: '302e020100300506032b65700422042031e943e883bab5fd43071a90ab983c83e1b5cfd9981c6ac124512f012f0a5f69'
            - name: MONGO_URI
              value: 'mongodb://did-mongo-srv:27017/did'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: did-srv
spec:
  selector:
    app: did
  ports:
    - name: did
      protocol: TCP
      port: 3000
      targetPort: 3000