apiVersion: apps/v1
kind: Deployment
metadata:
  name: did-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: did
  template:
    metadata:
      labels:
        app: did
    spec:
      containers:
        - name: did
          image: fibrinlab/did
          env:
            - name: MONGO_URI
              value: 'mongodb://did-mongo-srv:27017/did'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: did-srv
spec:
  selector:
    app: did
  ports:
    - name: did
      protocol: TCP
      port: 3000
      targetPort: 3000